"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = [
    ('assets', ['assets/tray_icon.png', 'assets/tray_icon@2x.png'])
]
OPTIONS = {
    'argv_emulation': False, # Recommended for PyQt apps
    'plist': {
        'LSUIElement': True, # Hide from Dock (Accessory App)
        'NSAccessibilityUsageDescription': 'DONE needs Accessibility permissions to monitor active applications and automate shortcuts.',
        'CFBundleName': 'DONE',
        'CFBundleDisplayName': 'DONE',
        'CFBundleIdentifier': 'com.jds.done',
        'CFBundleVersion': '1.0.0',
        'CFBundleShortVersionString': '1.0.0',
    },
    'packages': ['PyQt6', 'ollama', 'pydantic', 'pynput'],
    'includes': ['PyQt6.QtCore', 'PyQt6.QtGui', 'PyQt6.QtWidgets'],
    'iconfile': 'assets/icon.icns',
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
